/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package transaksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import java.io.File;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.awt.Desktop;
/**
 *
 * @author akbar
 */
public class FormLihatTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form FormLihatTransaksi
     */
    public FormLihatTransaksi() {
        initComponents();
        setLocationRelativeTo(null);
        tampilData();
    }
    
    private void tampilData() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID Reservasi");
        model.addColumn("ID Tamu");
        model.addColumn("ID Kamar");
        model.addColumn("Check-In");
        model.addColumn("Check-Out");
        model.addColumn("Total Biaya");
        model.addColumn("DP Dibayar");    // KOLOM BARU
        model.addColumn("Sisa Tagihan");  // KOLOM BARU
        model.addColumn("Status Bayar");
        model.addColumn("Status Reservasi");

        try {
            java.sql.Connection conn = koneksi.getkoneksi(); 
            java.sql.Statement st = conn.createStatement();
            String sql = "SELECT * FROM reservasi ORDER BY id_reservasi DESC"; 
            java.sql.ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_reservasi"),
                    rs.getString("id_tamu"),
                    rs.getString("id_kamar"),
                    rs.getString("tanggal_checkin"),
                    rs.getString("tanggal_checkout"),
                    rs.getString("total_bayar"), 
                    rs.getString("dp_dibayar"),
                    rs.getString("sisa_tagihan"),
                    rs.getString("status_pembayaran"),
                    rs.getString("status_reservasi")
                });
            }
            jTable1.setModel(model);
            autoFitTable(jTable1);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data transaksi: " + e.getMessage());
        }
    }
    
    private void autoFitTable(javax.swing.JTable table) {
        // Matikan fungsi pembagian lebar rata bawaan Java
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        
        javax.swing.table.TableColumnModel columnModel = table.getColumnModel();
        
        // Looping untuk mengecek setiap kolom
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 50; // Lebar minimal kolom
            
            // 1. Cek seberapa panjang teks pada Judul Kolom (Header)
            javax.swing.table.TableCellRenderer headerRenderer = table.getTableHeader().getDefaultRenderer();
            java.awt.Component headerComp = headerRenderer.getTableCellRendererComponent(
                    table, columnModel.getColumn(column).getHeaderValue(), false, false, 0, column);
            width = Math.max(width, headerComp.getPreferredSize().width);

            // 2. Cek seberapa panjang teks pada setiap baris data di kolom tersebut
            for (int row = 0; row < table.getRowCount(); row++) {
                javax.swing.table.TableCellRenderer renderer = table.getCellRenderer(row, column);
                java.awt.Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width, width);
            }
            
            // 3. Terapkan lebar terpanjang yang ditemukan ditambah sedikit jarak (padding 15px)
            columnModel.getColumn(column).setPreferredWidth(width + 15);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SLEEPWELL");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistem Reservasi Hotel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(245, 242, 250));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Cari :");

        jButton1.setText("CARI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(241, 196, 15));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("PRINT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 102, 153));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("TAMBAH TRANSAKSI");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(231, 76, 60));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("HAPUS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 153, 153));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("CETAK INVOICE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        FormTransaksi ft = new FormTransaksi();
        ft.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID Reservasi");
        model.addColumn("ID Tamu");
        model.addColumn("ID Kamar");
        model.addColumn("Check-In");
        model.addColumn("Check-Out");
        model.addColumn("Total Biaya");
        model.addColumn("DP Dibayar");    // KOLOM BARU
        model.addColumn("Sisa Tagihan");  // KOLOM BARU
        model.addColumn("Status Bayar");
        model.addColumn("Status Reservasi");

        try {
            java.sql.Connection conn = koneksi.getkoneksi();
            String sql = "SELECT * FROM reservasi WHERE id_reservasi LIKE ? OR id_tamu LIKE ? OR id_kamar LIKE ?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            String keyword = "%" + jTextField1.getText() + "%";
            pst.setString(1, keyword);
            pst.setString(2, keyword);
            pst.setString(3, keyword);
            
            java.sql.ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_reservasi"),
                    rs.getString("id_tamu"),
                    rs.getString("id_kamar"),
                    rs.getString("tanggal_checkin"),
                    rs.getString("tanggal_checkout"),
                    rs.getString("total_bayar"), 
                    rs.getString("dp_dibayar"),
                    rs.getString("sisa_tagihan"),
                    rs.getString("status_pembayaran"),
                    rs.getString("status_reservasi")
                });
            }
            jTable1.setModel(model);
            autoFitTable(jTable1);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal mencari data: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Silakan klik/pilih data di tabel terlebih dahulu!");
            return;
        }

        // 2. Tampilkan Pop-up Input Password (Disensor)
        javax.swing.JPasswordField pf = new javax.swing.JPasswordField();
        int okCxl = JOptionPane.showConfirmDialog(this, pf, "Masukkan Password Admin untuk Menghapus:", 
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);

        if (okCxl == JOptionPane.OK_OPTION) {
            String password = new String(pf.getPassword());

            // 3. Validasi Password (Anda bisa mengganti "admin123" dengan password Anda sendiri)
            if (password.equals("admin123")) {
                try {
                    // Ambil ID Reservasi (Kolom 0) dan ID Kamar (Kolom 2) dari tabel
                    String idReservasi = jTable1.getValueAt(row, 0).toString();
                    String idKamar = jTable1.getValueAt(row, 2).toString();
                    
                    java.sql.Connection conn = koneksi.getkoneksi();
                    
                    // Eksekusi Hapus dari tabel reservasi
                    String sqlHapus = "DELETE FROM reservasi WHERE id_reservasi=?";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sqlHapus);
                    pst.setString(1, idReservasi);
                    pst.executeUpdate();
                    
                    // Kembalikan status kamar menjadi 'Tersedia' karena transaksinya dihapus
                    String sqlKamar = "UPDATE kamar SET status_kamar='Tersedia' WHERE id_kamar=?";
                    java.sql.PreparedStatement pst2 = conn.prepareStatement(sqlKamar);
                    pst2.setString(1, idKamar);
                    pst2.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Data reservasi berhasil dihapus!");
                    tampilData(); // Refresh ulang tabel agar datanya hilang dari layar

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
                }
            } else {
                // Jika password salah
                JOptionPane.showMessageDialog(this, "Password Salah! Gagal menghapus.", "Akses Ditolak", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // 1. Cek apakah ada baris yang dipilih
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Silakan klik/pilih data di tabel yang ingin diedit!");
            return;
        }

        // 2. Tampilkan Pop-up Input Password (Disensor)
        javax.swing.JPasswordField pf = new javax.swing.JPasswordField();
        int okCxl = JOptionPane.showConfirmDialog(this, pf, "Masukkan Password Admin untuk Mengedit:", 
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);

        if (okCxl == JOptionPane.OK_OPTION) {
            String password = new String(pf.getPassword());

            // 3. Validasi Password
            if (password.equals("admin123")) {
                
                // Ambil ID Reservasi yang dipilih
                String idReservasi = jTable1.getValueAt(row, 0).toString();
                
                FormEditTransaksi editForm = new FormEditTransaksi(idReservasi);
                editForm.setVisible(true);
                this.dispose();
                
                // Untuk sementara, munculkan pesan berhasil login:
                JOptionPane.showMessageDialog(this, "Akses Edit Dibuka untuk ID: " + idReservasi);

            } else {
                JOptionPane.showMessageDialog(this, "Password Salah! Akses Edit Ditolak.", "Akses Ditolak", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Mulai meracik kode HTML
            StringBuilder html = new StringBuilder();
            html.append("<html><head><title>Laporan Transaksi</title>");
            
            // CSS (Style) agar tabel HTML terlihat rapi dan profesional
            html.append("<style>");
            html.append("body { font-family: 'Segoe UI', Tahoma, sans-serif; padding: 20px; }");
            html.append("table { width: 100%; border-collapse: collapse; margin-top: 20px; }");
            html.append("th, td { border: 1px solid #dddddd; padding: 10px; text-align: left; }");
            html.append("th { background-color: #2c3e50; color: white; }");
            html.append("h2 { color: #2c3e50; text-align: center; }");
            html.append("</style></head><body>");
            
            // Header Laporan
            html.append("<h2>Laporan Data Transaksi Hotel Sleepwell</h2>");
            html.append("<table><thead><tr>");

            // 2. Mengambil nama kolom (Header) dari JTable
            for (int i = 0; i < jTable1.getColumnCount(); i++) {
                html.append("<th>").append(jTable1.getColumnName(i)).append("</th>");
            }
            html.append("</tr></thead><tbody>");

            // 3. Mengambil isi data dari JTable
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                html.append("<tr>");
                for (int j = 0; j < jTable1.getColumnCount(); j++) {
                    Object cellValue = jTable1.getValueAt(i, j);
                    String text = (cellValue == null) ? "" : cellValue.toString();
                    html.append("<td>").append(text).append("</td>");
                }
                html.append("</tr>");
            }
            html.append("</tbody></table>");
            html.append("<br><p><i>Dicetak pada: ").append(new java.util.Date().toString()).append("</i></p>");
            html.append("</body></html>");

            // 4. Menyimpan kode HTML tadi ke dalam sebuah file
            File file = new File("Laporan_Transaksi_Sleepwell.html");
            BufferedWriter bw = new BufferedWriter(new FileWriter(file));
            bw.write(html.toString());
            bw.close();

            // 5. Menawarkan pop-up konfirmasi Print / Save PDF
            int confirm = JOptionPane.showConfirmDialog(this, 
                    "Data berhasil diekspor ke HTML!\n\nApakah Anda ingin membukanya di Browser sekarang?\n(Di browser, tekan Ctrl+P untuk Print atau Simpan sebagai PDF)", 
                    "Print / Simpan PDF", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            // 6. Jika user memilih "YES", buka file HTML tersebut di browser bawaan laptop
            if (confirm == JOptionPane.YES_OPTION) {
                if (Desktop.isDesktopSupported()) {
                    Desktop.getDesktop().browse(file.toURI());
                } else {
                    JOptionPane.showMessageDialog(this, "Sistem tidak mendukung pembukaan otomatis. Silakan buka file 'Laporan_Transaksi_Sleepwell.html' secara manual.");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mencetak laporan: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih data transaksi di tabel terlebih dahulu!");
            return;
        }

        // Ambil data dasar dari tabel (INDEKS SUDAH DISESUAIKAN)
        String idReservasi = jTable1.getValueAt(row, 0).toString();
        String idTamu = jTable1.getValueAt(row, 1).toString();
        String idKamar = jTable1.getValueAt(row, 2).toString();
        String tglCheckIn = jTable1.getValueAt(row, 3).toString();
        String tglCheckOut = jTable1.getValueAt(row, 4).toString();
        String totalBiaya = jTable1.getValueAt(row, 5).toString();
        String dpDibayar = jTable1.getValueAt(row, 6).toString();    
        String sisaTagihan = jTable1.getValueAt(row, 7).toString();  
        String statusBayar = jTable1.getValueAt(row, 8).toString();  

        String namaTamu = "-", nomorKamar = "-", tipeKamar = "-";

        try {
            java.sql.Connection conn = koneksi.getkoneksi();
            
            // Cari Nama Tamu
            java.sql.PreparedStatement pstTamu = conn.prepareStatement("SELECT nama_tamu FROM tamu WHERE id_tamu=?");
            pstTamu.setString(1, idTamu);
            java.sql.ResultSet rsTamu = pstTamu.executeQuery();
            if (rsTamu.next()) namaTamu = rsTamu.getString("nama_tamu");

            // Cari Detail Kamar
            java.sql.PreparedStatement pstKamar = conn.prepareStatement("SELECT nomor_kamar, tipe_kamar FROM kamar WHERE id_kamar=?");
            pstKamar.setString(1, idKamar);
            java.sql.ResultSet rsKamar = pstKamar.executeQuery();
            if (rsKamar.next()) {
                nomorKamar = rsKamar.getString("nomor_kamar");
                tipeKamar = rsKamar.getString("tipe_kamar");
            }

            // Meracik Desain HTML Invoice
            StringBuilder html = new StringBuilder();
            html.append("<html><head><title>Invoice - ").append(idReservasi).append("</title>");
            html.append("<style>");
            html.append("body { font-family: 'Segoe UI', Tahoma, Arial, sans-serif; background: #f9f9f9; padding: 20px; }");
            html.append(".invoice-box { max-width: 800px; margin: auto; padding: 30px; border: 1px solid #ddd; background: #fff; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); }");
            html.append(".header { text-align: center; border-bottom: 2px solid #2c3e50; padding-bottom: 20px; margin-bottom: 20px; }");
            html.append(".header h1 { color: #2c3e50; margin: 0; font-size: 36px; letter-spacing: 2px; }");
            html.append(".header p { color: #7f8c8d; margin: 5px 0 0 0; font-size: 14px; }");
            html.append(".info-table { width: 100%; margin-bottom: 30px; }");
            html.append(".info-table td { padding: 5px; vertical-align: top; font-size: 15px; }");
            html.append(".details-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }");
            html.append(".details-table th, .details-table td { padding: 12px; border: 1px solid #ddd; text-align: left; font-size: 15px; }");
            html.append(".details-table th { background-color: #2c3e50; color: white; }");
            html.append(".total-row td { font-weight: bold; font-size: 16px; background-color: #ecf0f1; }");
            
            String warnaStatus = statusBayar.equalsIgnoreCase("Lunas") ? "#27ae60" : "#e74c3c";
            html.append(".status { font-weight: bold; color: ").append(warnaStatus).append("; }");
            html.append(".footer { text-align: center; margin-top: 40px; font-size: 13px; color: #95a5a6; border-top: 1px solid #eee; padding-top: 20px; }");
            html.append("</style></head><body>");

            html.append("<div class='invoice-box'>");
            html.append("<div class='header'><h1>SLEEPWELL HOTEL</h1><p>Jl. Daan Mogot No. 123, Jakarta Raya</p><p>Telp: (021) 12345678 | Email: info@sleepwell.com</p></div>");

            html.append("<table class='info-table'><tr>");
            html.append("<td><b>INVOICE KEPADA:</b><br><span style='font-size: 18px;'>").append(namaTamu).append("</span><br>ID Tamu: ").append(idTamu).append("</td>");
            html.append("<td style='text-align: right;'><b>No. Reservasi:</b> #").append(idReservasi).append("<br><b>Tanggal Cetak:</b> ").append(new java.text.SimpleDateFormat("dd MMM yyyy HH:mm").format(new java.util.Date())).append("</td>");
            html.append("</tr></table>");

            html.append("<table class='details-table'><thead><tr><th>Deskripsi Pesanan</th><th>Check-In</th><th>Check-Out</th><th>Subtotal</th></tr></thead><tbody><tr>");
            html.append("<td>Sewa Kamar Nomor: <b>").append(nomorKamar).append("</b><br><small>Tipe: ").append(tipeKamar).append("</small></td>");
            html.append("<td>").append(tglCheckIn).append("</td><td>").append(tglCheckOut).append("</td><td>Rp ").append(totalBiaya).append("</td></tr>");
            
            html.append("<tr class='total-row'><td colspan='3' style='text-align: right;'>TOTAL TAGIHAN</td><td>Rp ").append(totalBiaya).append("</td></tr>");
            html.append("<tr><td colspan='3' style='text-align: right;'>DP DIBAYARKAN</td><td>Rp ").append(dpDibayar).append("</td></tr>");
            html.append("<tr><td colspan='3' style='text-align: right;'>SISA TAGIHAN</td><td style='color: #e74c3c; font-weight: bold;'>Rp ").append(sisaTagihan).append("</td></tr>");
            html.append("<tr><td colspan='3' style='text-align: right;'>STATUS PEMBAYARAN</td><td class='status'>").append(statusBayar.toUpperCase()).append("</td></tr>");
            html.append("</tbody></table>");

            html.append("<div class='footer'><p><i>Terima kasih telah mempercayakan penginapan Anda di Sleepwell Hotel.</i></p></div>");
            html.append("</div></body></html>");

            java.io.File file = new java.io.File("Invoice_" + idReservasi + ".html");
            java.io.BufferedWriter bw = new java.io.BufferedWriter(new java.io.FileWriter(file));
            bw.write(html.toString());
            bw.close();

            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                    "Invoice berhasil dibuat!\n\nApakah Anda ingin membuka struk di Browser sekarang?", 
                    "Cetak Invoice Sukses", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.INFORMATION_MESSAGE);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                if (java.awt.Desktop.isDesktopSupported()) {
                    java.awt.Desktop.getDesktop().browse(file.toURI());
                }
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mencetak invoice: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLihatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLihatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLihatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLihatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLihatTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
